insert into category (name, category_type) VALUES
  ('Bhakti Poet','person'),
  ('Sufi Poet','person'),
  ('Baul Poet','person'),
  ('Mystic Poet','person'),
  ('Classical Singer','person'),
  ('Folk Singer','person'),
  ('Baul Singer','person'),
  ('Waai Singer','person'),
  ('Thumri Singer','person'),
  ('Qawwal','person'),
  ('Sufi Singer','person'),
  ('Bhakti Singer','person'),
  ('Writer','person'),
  ('Scholar','person'),
  ('Researcher','person'),
  ('Fiction Writer','person'),
  ('Translator','person'),
  ('Contemporary Poet','person'),
  ('Journalist','person'),
  ('Artist','person'),
  ('Painter','person'),
  ('Photographer','person'),
  ('Filmmaker','person'),
  ('Designer','person'),
  ('Animator','person'),
  ('Visual Artist','person'),
  ('Illustrator','person'),
  ('Graphic Novelist','person'),
  ('Philosopher','person'),
  ('Folklorist','person'),
  ('Thinker','person'),
  ('Social Activist','person'),
  ('Social Worker','person'),
  ('Ngo Worker','person'),
  ('Politician','person'),
  ('Political Worker','person'),
  ('Cultural Activist','person'),
  ('Dancer','person'),
  ('Media Artist','person'),
  ('Theatre Person','person'),
  ('Theatre Director','person'),
  ('Actor','person'),
  ('Performing Artist','person'),
  ('Educator','person'),
  ('Educationist','person'),
  ('Teacher','person'),
  ('School Teacher','person'),
  ('College Professor','person'),
  ('Farmer','person'),
  ('Fruit Seller','person'),
  ('Shop Keeper','person'),
  ('Paan Wallah','person'),
  ('Weaver','person'),
  ('Village Elder','person'),
  ('Ex-Bureaucrat','person'),
  ('Bureaucrat','person'),
  ('Institution Builder','person'),
  ('Home Maker','person'),
  ('Professional','person'),
  ('Entrepreneur','person'),
  ('Spiritual Leader','person'),
  ('Spiritual Practitioner','person'),
  ('Practitioner','person'),
  ('Seeker','person'),
  ('Guru','person'),
  ('Spiritual Guide','person'),
  ('Spiritual Figure','person'),
  ('Religious Leader','person'),
  ('Co-Traveller','person'),
  ('Yatri','person');